crudlab/urls.py
from django.contrib import admin
from django.urls import path,include
from core import views

urlpatterns = [
    path('',views.index,name="index"),
    path('v1/',include('v1.urls',namespace='v1')),
    path('v2/',include('v2.urls',namespace='v2')),
    path('admin/', admin.site.urls),

]

v1/urls.py
from django.urls import path 
from . import views

app_name="v1"
urlpatterns = [
    path('',views.index,name='index'),
    path('add/',views.add_product,name='add_product'),
    path('edit/<int:id>/',views.edit_product,name='edit_product'),
    path('delete/<int:id>/',views.delete_product,name='delete_product'),
]

v2/urls.py
app_name="v2"
urlpatterns=[
    
]

core/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    name=models.CharField(max_length=120,verbose_name="Product Title")
    sku=models.CharField(max_length=50,unique=True,verbose_name="Product Code")
    price=models.DecimalField(max_digits=10,decimal_places=2,verbose_name="Retail Price")
    stock_quantity=models.IntegerField(verbose_name="Units in Stock")
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name} ({self.sku})"

core/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model=Product
        fields=["name", "sku", "price", "stock_quantity"]
        widgets={
            'name':forms.TextInput(attrs={
                'class':'form_input',
                'placeholder':'e.g. Samsung Monitor'
            }),
            'sku': forms.TextInput(attrs={
                'class': 'form_input', 
                'placeholder': 'e.g. SM-4001'
            }),
            'price': forms.NumberInput(attrs={
                'class': 'form_input', 
                'placeholder': 'e.g. 199.99'
            }),
            'stock_quantity': forms.NumberInput(attrs={
                'class': 'form_input', 
                'placeholder': 'Available stock'
            }),
        }

core/views.py
from django.shortcuts import render,redirect

# Create your views here.
def index(request):
    return redirect("v1:index")

v1/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib import messages
from core.models import Product
from core.forms import ProductForm
# Create your views here.
def index(request):
    products=Product.objects.order_by("-id")
    return render(request,'pages/index.html',{
        "products":products,
        "page_title":"Home",
        "action_title":"home"
    })

def add_product(request):
    form=ProductForm(request.POST or None)
    if request.method=="POST":
        if form.is_valid():
            form.save()
            messages.success(request, "Product added successfully!")
            return redirect("v1:index")
        else:
            messages.error(request, "Error adding product. Please check the form.")
    return render(request,"pages/product_form.html",{
        "form":form,
        "action_title": "Save Product",
        "page_title":"Add Product"
    })

def edit_product(request,id):
    product=get_object_or_404(Product,id=id)
    form=ProductForm(request.POST or None, instance=product)
    if request.method=="POST":
        if form.is_valid():
            form.save()
            messages.success(request, "Product updated successfully!")
            return redirect("v1:index")
        else:
            messages.error(request, "Error updating product.")
    return render(request,'pages/product_form.html',{
        "form":form,
        "product":product,
        "action_title": "Update Product",
        "page_title":"Update Product"
        })

def delete_product(request,id):
    product=get_object_or_404(Product, id=id)
    if request.method=="POST":
        product.delete() 
        messages.success(request, "Product deleted successfully!")
    return redirect("v1:index")

v2/views.py
from django.shortcuts import render

# Create your views here.

v1/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/tailwind.css' %}" />
  </head>
  <body>
    <div class="max-w-4xl mx-auto mt-16">
      {% if messages %}
      <div class="mb-4">
        {% for message in messages %}
        <p
          class="p-3 rounded {% if message.tags == 'success' %} bg-green-100 text-green-800 {% elif message.tags == 'error' %} bg-red-100 text-red-800 {% else %} bg-gray-100 text-gray-800 {% endif %}"
        >
          {{ message }}
        </p>
        {% endfor %}
      </div>
      {% endif %}
      <!--  -->
      {% block content %} {% endblock %}
    </div>
  </body>
</html>

v1/templates/pages/index.html
<!--  -->
{% extends 'base.html' %}
<!--  -->
{% block title %} {{page_title}} {% endblock %}
<!--  -->
{% block content %}
<!-- Header -->
{% include 'util/header.html' with action=action_title %}
<div class="overflow-x-auto">
  <table class="min-w-xl md:min-w-full divide-y overflow-auto divide-gray-200">
    <thead class="bg-white">
      <tr>
        <th class="py-3 text-left text-sm font-medium text-gray-600">Name</th>
        <th class="py-3 text-left text-sm font-medium text-gray-600">SKU</th>
        <th class="py-3 text-left text-sm font-medium text-gray-600">Stock</th>
        <th class="py-3 text-left text-sm font-medium text-gray-600">Price</th>
        <th class="py-3 text-end text-sm font-medium text-gray600">Action</th>
      </tr>
    </thead>
    <tbody class="divide-y divide-gray-200">
      {% if products %}
      <!--  -->
      {% for product in products %}
      <tr>
        <td class="py-3 px-3 md:px-0 text-sm text-gray-900">{{product.sku}}</td>
        <td class="py-3 px-3 md:px-0 text-sm text-gray-600">
          {{product.name}}
        </td>
        <td class="py-3 px-3 md:px-0 text-sm text-gray-600">
          {{product.stock_quantity}}
        </td>
        <td class="py-3 px-3 md:px-0 text-sm text-gray-600">
          {{product.price}}
        </td>
        <td>
          <div class="flex gap-2 justify-end">
            <a
              href="{% url 'v1:edit_product' id=product.id %}"
              class="cursor-pointer"
            >
              <!-- prettier-ignore -->
              <svg width="20" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="#fbbf24">
              <path d="m5.433 13.917 1.262-3.155A4 4 0 0 1 7.58 9.42l6.92-6.918a2.121 2.121 0 0 1 3 3l-6.92 6.918c-.383.383-.84.685-1.343.886l-3.154 1.262a.5.5 0 0 1-.65-.65Z" />
              <path d="M3.5 5.75c0-.69.56-1.25 1.25-1.25H10A.75.75 0 0 0 10 3H4.75A2.75 2.75 0 0 0 2 5.75v9.5A2.75 2.75 0 0 0 4.75 18h9.5A2.75 2.75 0 0 0 17 15.25V10a.75.75 0 0 0-1.5 0v5.25c0 .69-.56 1.25-1.25 1.25h-9.5c-.69 0-1.25-.56-1.25-1.25v-9.5Z" />
            </svg>
            </a>

            <form
              method="post"
              action="{% url 'v1:delete_product' id=product.id %}"
              onsubmit="return confirm('Are you sure you want to delete?')"
              class="cursor-pointer"
            >
              {% csrf_token %}
              <button type="submit" class="cursor-pointer">
                <!-- prettier-ignore -->
                <svg width="20" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="#dc2626" className="size-5">
                 <path fillRule="evenodd" d="M8.75 1A2.75 2.75 0 0 0 6 3.75v.443c-.795.077-1.584.176-2.365.298a.75.75 0 1 0 .23 1.482l.149-.022.841 10.518A2.75 2.75 0 0 0 7.596 19h4.807a2.75 2.75 0 0 0 2.742-2.53l.841-10.52.149.023a.75.75 0 0 0 .23-1.482A41.03 41.03 0 0 0 14 4.193V3.75A2.75 2.75 0 0 0 11.25 1h-2.5ZM10 4c.84 0 1.673.025 2.5.075V3.75c0-.69-.56-1.25-1.25-1.25h-2.5c-.69 0-1.25.56-1.25 1.25v.325C8.327 4.025 9.16 4 10 4ZM8.58 7.72a.75.75 0 0 0-1.5.06l.3 7.5a.75.75 0 1 0 1.5-.06l-.3-7.5Zm4.34.06a.75.75 0 1 0-1.5-.06l-.3 7.5a.75.75 0 1 0 1.5.06l.3-7.5Z" clipRule="evenodd" />
               </svg>
              </button>
            </form>
          </div>
        </td>
      </tr>
      {% endfor %}
      <!--  -->
      {% else %}
      <tr>
        <td colspan="5" class="py-10 text-center text-gray-500 mt-3">
          No products found.
          <a
            href="{% url 'v1:add_product' %}"
            class="text-neutral-600 font-bold underline"
            >Add one now?</a
          >
        </td>
      </tr>
      {% endif %}
    </tbody>
  </table>
</div>
<!--  -->
{% endblock %}

v1/templates/pages/product_form.html
{% extends 'base.html' %}
<!--  -->
{% block title %} {{ page_title }} {% endblock %}
<!--  -->
{% block content %}
<form method="post">
  {% include 'util/header.html' with action=action_title %}

  <div id="add_form">
    {% csrf_token %}
    <!--  -->
    {% for field in form %}
    <div class="mb-5">
      <label
        for="{{ field.id_for_label }}"
        class="block text-sm font-medium text-gray-600 mb-1"
      >
        {{ field.label | default_if_none:'' }}
      </label>

      {{ field }}
      <!--  -->
      {% if field.errors %}
      <p class="text-red-500 text-sm mt-1">{{ field.errors.0 }}</p>
      {% endif %}
    </div>
    {% endfor %}
  </div>
</form>
{% endblock %}

v1/templates/util/header.html
<div class="flex flex-col md:flex-row items-center justify-between mb-6">
  <div>
    <h2 class="text-2xl font-semibold text-gray-900">
      <a href="{% url 'v1:index' %}">Product Management Panel.</a>
    </h2>
    <p class="text-sm text-gray-600">
      Create, update,delete, and track product information.
    </p>
  </div>

  {% if action == "home" %}
  <a
    href="{% url 'v1:add_product' %}"
    type="submit"
    class="mt-4 md:mt-0 px-4 py-2 bg-neutral-600 text-white rounded-md shadow hover:bg-neutral-700 cursor-pointer"
  >
    + Add Product
  </a>
  {% else %}
  <button
    type="submit"
    class="mt-4 md:mt-0 px-4 py-2 bg-neutral-600 text-white rounded-md shadow hover:bg-neutral-700 cursor-pointer"
  >
    {{action}}
  </button>
  {% endif %}
</div>